colorScheme = "congo"
# logo = "img/logo.jpg"
# description = "My awesome website"
# mainSections = ["section1", "section2"]
# robots = ""

[homepage]
  layout = "profile"
  showRecent = false

[article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  # sharingLinks = ["facebook", "twitter", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = false
  groupByYear = true

[taxonomy]
  showTermCount = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
